# Site
title:              अक्षित अरोड़ा | Akshit Arora | ਅਕ੍ਸ਼ਿਤ ਅਰੋੜਾ
bio:                'I am a graduate student in Computer Science at CUBoulder<br>Interested in Artificial Intelligence, Deep Learning and Photography!<br><a href="mailto:akshit.arora@colorado.edu">akshit [dot] arora [at] colorado [dot] edu</a>'
description:        "Artificial Intelligence, Deep Learning and Photography" #will be changed 
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://aroraakshit.github.io/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   https-aroraakshit-github-io

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:              akshit.arora@colorado.edu
twitter:            AkshitArora1995
facebook:           AkshitArora1995
github-url:         aroraakshit
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           akshitarora1995
#xing:              username
instagram:          akshit1995
#lastfm:            username
tumblr:            aarora
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
flickr:             akshitarora
a500px:              akshitarora
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
