# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AkshitArora
email: akshit.arora1995@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  It's where I put the cool stuff (my experiments) that I do in topics like Machine Learning and Artificial Intelligence. I am inspired by a number of bloggers around the world like Frob Yard (by Siddha Ganju http://sidgan.me), Paul Stamatiou (http://paulstamatiou.com) etc.
baseurl: ""
url: "http://akshitarora.github.io" # the base hostname & protocol for your site
twitter_username: akshitarora1995
github_username:  akshitarora

# Build settings
markdown: kramdown

#additional settings from http://jekyllrb.com/docs/configuration/
timezone: IN
author: Akshit Arora
tumblr_username: aarora
flickr_username:  akshitarora
facebook_username:  akshitarora1995
500px_username:  akshitarora
instagram_username: akshit1995
linkedin_username: akshitarora1995